CREATE DATABASE bill_payments;

CREATE TABLE USERS (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(70) NOT NULL, 
	LASTNAME VARCHAR(70) NOT NULL, 
	PHONE_NUMBER VARCHAR(15) NULL,
	ADDRESS VARCHAR(150) NULL,
	PRIMARY KEY (ID)
	);

CREATE TABLE BANKS (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	NIT VARCHAR(10) NOT NULL,
	PHONE_NUMBER VARCHAR(15) NULL,
	PRIMARY KEY(ID),
	UNIQUE (NIT)
); 

CREATE TABLE BILL_PAYMENTS (
	ID INT NOT NULL AUTO_INCREMENT,
	AMOUNT DOUBLE NOT NULL,
	EXPIRED_DATE DATETIME NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	IS_PAID BOOLEAN NOT NULL,
	USER_ID INT NOT NULL,
	BANK_ID INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
	FOREIGN KEY (BANK_ID) REFERENCES BANKS(ID)
);

CREATE TABLE PAYS (
	ID INT NOT NULL AUTO_INCREMENT,
	PAID_DATE DATETIME NOT NULL,
	VALUE DOUBLE NOT NULL,
	BILL_PAYMENT_ID INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (BILL_PAYMENT_ID) REFERENCES BILL_PAYMENTS(ID)
);